### ISSUE TITLE
ActionPanel，UIView viewContext不一致的问题

### ISSUE THREAD

**Issue by uraincay** [ecomfe/ef#42]
UIView上渲染了一些控件，现在在ActionPanel里只能通过actionPanel.action.view.get(controlId)去拿，
想用这种写法actionPanel.viewContext.get(controlId)，但是两者的viewContext不是一个。前一种写法嵌套层级一深，写法会比较痛苦。
有办法能让两者的viewContext是一个吗？我看UIView有一个this.name, 但是不知道怎么设上这个name，希望大神指点。

**Comment by Justineo** [comment]
`ActionPanel` 内部的逻辑能不能不要暴露给外面呢？而是通过一些事件机制来完成业务交互？

**Comment by uraincay** [comment]
谢回复。我指的是actionPanel的内部逻辑想要得到uiVIew里面的控件，然后操作

**Comment by otakustay** [comment]
我们不会做这些改变，因为一个ActionPanel加载的Action是任意且未知的，如我们通过用户自定义模板来加载一个子Action。此时无法确保子Action中的控件的id不会与ActionPanel所在的ViewContext冲突，因此这一隔离是必须的

如果你确实需要达到你的目的，让你的View重写createViewContext方法，可以想办法让外层把ViewContext的名称传过来，从而用er/ViewContext.get获取出来

但依旧不建议这么玩



Best regards

Gray Zhang



在 2015年3月20日 下午4:16:36, uraincay (notifications@github.com) 写到:

谢回复。我指的是actionPanel的内部逻辑想要得到uiVIew里面的控件，然后操作

**Comment by uraincay** [comment]
明白。刻意这么设计，为了隔离。
感觉已经在ActionPanel--->UIView--->ActionPanel--->UIView的逻辑中迷失。
借楼多问一个问题，一段复杂业务的功能块，是应该写成一个控件（包含很多子控件）还是子action（可以在template中写很多控件）怎么划分两者的界限？
当前我认为是有无数据请求，求解答。

**Comment by otakustay** [comment]
我一般就是按有无数据请求来分的



Best regards

Gray Zhang



在 2015年3月20日 下午7:18:34, uraincay (notifications@github.com) 写到:

明白。刻意这么设计，为了隔离。
感觉已经在ActionPanel--->UIView--->ActionPanel--->UIView的逻辑中迷失。
借楼多问一个问题，一段复杂业务的功能块，是应该写成一个控件（包含很多子控件）还是子action（可以在template中写很多控件）怎么划分两者的界限？
当前我认为是有无数据请求，求解答。

**Comment by uraincay** [comment]
好的！谢
